apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-deploy
spec:
  type: LoadBalancer
  selector:
    app: nginx-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000